
###
GET http://localhost:3000/todos/?status=TO%20DO

###

GET http://localhost:3000/todos/?priority=HIGH

###
GET http://localhost:3000/todos/?status=TO%20DO&priority=LOW
###
GET http://localhost:3000/todos/?search_q=css

###
GET http://localhost:3000/todos/2/

###
POST http://localhost:3000/todo/ 
Content-Type: Application/json
 
{
  "id": 10,
  "todo": "Finalize event theme",
  "priority": "LOW",
  "status": "TO DO"
}

###
PUT http://localhost:3000/todos/1/
Content-Type:application/json 

   {
      "priority": "HIGH"
    }

###
DELETE http://localhost:3000/todos/1/
